aborting if changes not excl in specified dirs

diff --git a/.github/workflows/firebase-functions-merge.yml b/.github/workflows/firebase-functions-merge.yml
--- a/.github/workflows/firebase-functions-merge.yml
+++ b/.github/workflows/firebase-functions-merge.yml
@@ -28,32 +28,45 @@ jobs:
           echo "Files outside the 'functions' directory: $OUTSIDE_PUBLIC"
           
           # If there are files outside 'functions', fail the action
-          if [ -n "$OUTSIDE_FUNCTIONS" ]; then
-            echo "Deployment aborted: Changes detected outside 'functions' folder."
+          if [ -z "$CHANGED_FILES" ]; then
+            echo "No changes detected. Skipping deployment."
+            exit 1
+          elif [ -n "$OUTSIDE_FUNCTIONS" ]; then
+            echo "Deployment aborted: Changes detected outside 'public' folder."
             exit 1
           else
             echo "Only 'functions' folder was changed. Proceeding with deployment."
           fi
+
       - name: Set up Node.js
         uses: actions/setup-node@v3  # Set up Node.js 
         with:
-          node-version: '18'  # Use Node.js version 16
+          node-version: '18'  # Use Node.js version 18 as in project
+          continue-on-error: false
 
       - name: Install Dependencies from 'functions' Directory
         run: |
           cd functions
           npm install 
+        with:
+          continue-on-error: false
 
       - name: Install Firebase CLI
         run: npm install -g firebase-tools  # Install Firebase CLI globally
+        with:
+          continue-on-error: false
 
       - name: Authenticate with Firebase
         run: echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_SALE_CHECK_B611B }}" > $HOME/firebase-key.json  # Authenticate with Firebase using my service account
+        with:
+          continue-on-error: false
         env:
           FIREBASE_SERVICE_ACCOUNT_SALE_CHECK_B611B: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SALE_CHECK_B611B }}
 
       - name: Deploy Firebase Functions
         run: firebase deploy --only functions  # Run deploy only for functions
+        with:
+          continue-on-error: false
         env:
           GOOGLE_APPLICATION_CREDENTIALS: $HOME/firebase-key.json  # Points to my Firebase service account key
           FIREBASE_TOKEN: ${{ secrets.FIREBASE_AUTH_TOKEN }}  # (Optional) If you store the Firebase auth token as a secret
