Update formatting

diff --git a/.github/workflows/npm-audit.yml b/.github/workflows/npm-audit.yml
--- a/.github/workflows/npm-audit.yml
+++ b/.github/workflows/npm-audit.yml
@@ -12,15 +12,15 @@ jobs:
   npm-audit:
     runs-on: ubuntu-latest
     steps:
-      - name: Checkout code
+      - name: Checkout Code
         uses: actions/checkout@v4
 
-      - name: Set up Node.js
+      - name: Set Up Node.js
         uses: actions/setup-node@v3
         with:
           node-version: '22'
 
-      - name: Install dependencies
+      - name: Install Dependencies
         run: |
           cd ${{ inputs.working-directory }}
           npm install
@@ -42,11 +42,11 @@ jobs:
             echo "::error:: Critical vulnerabilities found: $critical_count"
             echo "::error:: High vulnerabilities found: $high_count"
             echo "$audit_output"
-            # exit 1
+            exit 1
           elif [ "$critical_count" -gt 0 ]; then
             echo "::error:: Critical vulnerabilities found: $critical_count"
             echo "$audit_output"
-            # exit 1
+            exit 1
           elif [ "$high_count" -gt 0 ]; then
             echo "::error:: High vulnerabilities found: $high_count"
             echo "$audit_output"
@@ -54,15 +54,15 @@ jobs:
           elif [ "$critical_count" -eq 0 ] && [ "$high_count" -eq 0 ] && [ "$vuln_count" -gt 0 ]; then
             echo "::warning:: Non-severe vulnerabilities found: $vuln_count"
             echo "$audit_output"
-            # exit 0
+            exit 0
           elif [ "$vuln_count" -eq 0 ] && [ "$high_count" -eq 0 ] && [ "$critical_count" -eq 0 ]; then
             echo "No vulnerabilities found."
-            # exit 0
+            exit 0
           else
-            echo ":error: Security Scan Failed!"
+            echo "::error:: Security Scan Failed with Unknown Reason!"
             echo "Terminating the workflow due to unknown state of security."
             echo "$audit_output"
-            # exit 1
+            exit 1
           fi
 
           echo "::notice:: Security scan complete."
